# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Nathan M. Fraske, Critical Error Computing L.L.C.
#
# Build-GigabyteMapping.ps1 - regenerate Gigabyte rows in config/mapping.json by
# enumerating the catalog via the modellist API (model -> rev-slug -> support
# page). NETWORK-GATED: run manually or in the scheduled job, never in the offline
# unit suite. www.gigabyte.com is behind Akamai and blocks datacenter IPs, so
# this is best run from a normal network. Non-Gigabyte rows are preserved.
#
#   pwsh -File tools/Build-GigabyteMapping.ps1            # update config/mapping.json
#   pwsh -File tools/Build-GigabyteMapping.ps1 -WhatIf    # show counts, write nothing

[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $MappingPath,
    [int]    $MaxPages = 200
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path $root 'src/Common.psm1') -Force
Import-Module (Join-Path $root 'src/Mapping.psm1') -Force
Import-Module (Join-Path $root 'src/providers/Gigabyte.psm1') -Force

if (-not $MappingPath) { $MappingPath = Join-Path $root 'config/mapping.json' }
$s = Get-Settings
$perPage = [int]$s.gigabyte.modelListPerPage
if ($perPage -le 0) { $perPage = 16 }
$headers = Get-GigabyteHeaders
$headers['Content-Type'] = 'application/json'
$headers['Origin'] = 'https://www.gigabyte.com'
$headers['Referer'] = 'https://www.gigabyte.com/Motherboard/All-Series'

$rows = @{}
$page = 1
$pages = 1
do {
    $body = (@{ page = $page; fid = ''; order = 0; length = 50 } | ConvertTo-Json -Compress)
    Write-Host "Fetching modellist page $page ..."
    $resp = Invoke-Http -Url $s.gigabyte.modelListUrl -Method POST -Body $body -ContentType 'application/json' -Headers $headers
    $parsed = ConvertFrom-GigabyteModelList -JsonText $resp
    if (@($parsed).Count -eq 0) { break }
    if ($page -eq 1) {
        $total = [int]$parsed[0].TotalRow
        if ($total -gt 0) { $pages = [Math]::Min($MaxPages, [Math]::Ceiling($total / $perPage)) }
        Write-Host ("Catalog: {0} models across {1} page(s)." -f $total, $pages)
    }
    foreach ($m in $parsed) { $rows[$m.Model] = $m }
    $page++
    Start-Sleep -Milliseconds 400   # be polite to Akamai
} while ($page -le $pages)

Write-Host ("Collected {0} Gigabyte models." -f $rows.Count)
if ($rows.Count -eq 0) { throw 'No Gigabyte models retrieved (Akamai may have blocked this IP; run from a normal network).' }

# Preserve existing non-Gigabyte rows; rebuild Gigabyte rows.
$entries = [ordered]@{}
if (Test-Path -LiteralPath $MappingPath) {
    $existing = Get-Content -LiteralPath $MappingPath -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($existing.PSObject.Properties['entries']) {
        foreach ($p in $existing.entries.PSObject.Properties) {
            if ([string]$p.Value.vendor -ne 'gigabyte') { $entries[$p.Name] = $p.Value }
        }
    }
}
$today = Get-Date -Format 'yyyy-MM-dd'
foreach ($m in $rows.Values) {
    $entries[$m.Model] = [ordered]@{
        vendor = 'gigabyte'; model = $m.Model; method = 'gigabyte-html'; slug = $m.Slug
        downloadPage = $m.SupportUrl; lastVerified = $today
    }
}

Write-Host ("Prepared {0} total mapping entries." -f $entries.Count)
if ($PSCmdlet.ShouldProcess($MappingPath, "write $($entries.Count) mapping entries")) {
    ([ordered]@{ _comment = 'Model -> vendor cache. Gigabyte rows regenerated by tools/Build-GigabyteMapping.ps1.'; entries = $entries } |
        ConvertTo-Json -Depth 6) | Set-Content -LiteralPath $MappingPath -Encoding UTF8
    Write-Host "Wrote $MappingPath"
}
