# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Nathan M. Fraske, Critical Error Computing L.L.C.
#
# Build-AsusMapping.ps1 - regenerate ASUS rows in config/mapping.json from the
# ASUS catalog (one SeriesFilterResult call -> ~897 boards). NETWORK-GATED: run
# manually or in a scheduled job, never in the offline unit suite. Non-ASUS rows
# and curated entries are preserved.
#
#   pwsh -File tools/Build-AsusMapping.ps1               # update config/mapping.json
#   pwsh -File tools/Build-AsusMapping.ps1 -WhatIf       # show counts, write nothing

[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $MappingPath
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path $root 'src/Common.psm1') -Force
Import-Module (Join-Path $root 'src/Mapping.psm1') -Force

if (-not $MappingPath) { $MappingPath = Join-Path $root 'config/mapping.json' }

$s = Get-Settings
$url = ('{0}/SeriesFilterResult?SystemCode={1}&WebsiteCode={2}&ProductLevel1Code=Motherboards-Components&ProductLevel2Code=Motherboards' -f `
    ($s.asus.pdInfoBase -replace '/PDInfo$', ''), $s.asus.systemCode, $s.asus.websiteCode)

Write-Host "Fetching ASUS catalog..."
$body = Invoke-Http -Url $url
$list = ($body | ConvertFrom-Json).Result.ProductList
Write-Host ("ASUS catalog: {0} boards." -f @($list).Count)

# Preserve existing entries; rebuild ASUS rows.
$entries = [ordered]@{}
if (Test-Path -LiteralPath $MappingPath) {
    $existing = Get-Content -LiteralPath $MappingPath -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($existing.PSObject.Properties['entries']) {
        foreach ($p in $existing.entries.PSObject.Properties) {
            if ([string]$p.Value.vendor -ne 'asus') { $entries[$p.Name] = $p.Value }
        }
    }
}

$today = Get-Date -Format 'yyyy-MM-dd'
$added = 0
foreach ($e in $list) {
    $model = [string]$e.SalesModelName
    if (-not $model) { $model = [string]$e.CategoryName }
    if (-not $model) { continue }
    $page = [string]$e.ProductURL
    if ($page) { $page = ($page.TrimEnd('/') + '/helpdesk_download/') }
    $entries[$model] = [ordered]@{
        vendor       = 'asus'
        model        = $model
        method       = 'asus-api'
        slug         = $null
        pdhashedid   = [string]$e.ProductHashedID
        downloadPage = $page
        lastVerified = $today
    }
    $added++
}

Write-Host ("Prepared {0} ASUS rows ({1} total entries)." -f $added, $entries.Count)
if ($PSCmdlet.ShouldProcess($MappingPath, "write $($entries.Count) mapping entries")) {
    $doc = [ordered]@{
        _comment = 'Model -> vendor cache. ASUS rows regenerated by tools/Build-AsusMapping.ps1. See docs/architecture.md.'
        entries  = $entries
    }
    $doc | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $MappingPath -Encoding UTF8
    Write-Host "Wrote $MappingPath"
}
